Repository codestates-seb/seb40_main_006, pull requests merged in 2022-12, with the labels that each got.

#110 [client] 잼 상세페이지 대댓글 기능, 잼 수정, 삭제 통신 로직 구현
  client/package-lock.json
  client/src/App.js
  client/src/Components/Header/Header.js
  client/src/Components/jamCreateComponent/AddressModal.js
  client/src/Components/jamCreateComponent/Description.js
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamCreateComponent/JamInputField.js
  client/src/Components/jamCreateComponent/StudyInputField.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamComments.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReplyComment.js
  client/src/Components/jamDetailComponent/ReplyComment.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
  client/src/Utils/customAxios.js
  client/src/customAxios.js
  client/src/setupProxy.js
Labels: :sparkles: feat, 🔍 chore, [FE]김정구

#113 [server] 오픈채팅 링크 수정하기 추가
  server/src/main/java/com/jamit/jam/service/JamService.java
Labels: :sparkles: feat, [BE]손경은

#115 [server] yml 설정 추가 및 수정
  server/src/main/resources/application.yml
  server/src/main/resources/aws.yml
Labels: 🔍 chore, [BE]손경은

#116 [server] Reply CUD 구현
  server/src/main/java/com/jamit/exception/ExceptionCode.java
  server/src/main/java/com/jamit/reply/controller/ReplyController.java
  server/src/main/java/com/jamit/reply/dto/ReplyPatchDto.java
  server/src/main/java/com/jamit/reply/dto/ReplyPostDto.java
  server/src/main/java/com/jamit/reply/dto/ReplyResponseDto.java
  server/src/main/java/com/jamit/reply/dto/ResponseReplyDto.java
  server/src/main/java/com/jamit/reply/entity/Reply.java
  server/src/main/java/com/jamit/reply/mapper/ReplyMapper.java
  server/src/main/java/com/jamit/reply/repository/ReplyRepository.java
  server/src/main/java/com/jamit/reply/service/ReplyService.java
Labels: :sparkles: feat, [BE]손경은

#118 [client] 지역별 잼 조회 기능 구현
  client/src/Components/Category/JamCard.js
  client/src/Components/Category/LongJamCard.js
  client/src/Components/Map/Map.js
  client/src/Components/NoData.js
  client/src/Pages/Home.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#122 [server] 유저 평점 부여
  server/src/main/generated/com/jamit/comment/mapper/CommentMapperImpl.java
  server/src/main/generated/com/jamit/jam/mapper/JamMapperImpl.java
  server/src/main/generated/com/jamit/location/mapper/LocationMapperImpl.java
  server/src/main/generated/com/jamit/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/jamit/reply/mapper/ReplyMapperImpl.java
  server/src/main/java/com/jamit/JamitApplication.java
  server/src/main/java/com/jamit/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/jamit/exception/ExceptionCode.java
  server/src/main/java/com/jamit/location/service/LocationService.java
  server/src/main/java/com/jamit/member/controller/MemberController.java
  server/src/main/java/com/jamit/member/dto/GradePostDto.java
  server/src/main/java/com/jamit/member/dto/ProfileDto.java
  server/src/main/java/com/jamit/member/entity/Member.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
  server/src/main/java/com/jamit/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: :sparkles: feat, [BE]이지연

#129 [server] 좌표 검색 리팩토링
  server/src/main/generated/com/jamit/comment/mapper/CommentMapperImpl.java
  server/src/main/generated/com/jamit/jam/mapper/JamMapperImpl.java
  server/src/main/generated/com/jamit/location/mapper/LocationMapperImpl.java
  server/src/main/generated/com/jamit/member/mapper/MemberMapperImpl.java
  server/src/main/generated/com/jamit/reply/mapper/ReplyMapperImpl.java
  server/src/main/java/com/jamit/jam/dto/JamPostDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseAllJamsDto.java
  server/src/main/java/com/jamit/jam/mapper/JamMapper.java
  server/src/main/java/com/jamit/member/service/MemberService.java
Labels: 🔧 refactor, [BE]이지연

#131 [server] login response에 유저 평점 추가
  server/src/main/java/com/jamit/JamitApplication.java
  server/src/main/java/com/jamit/auth/dto/LoginResponseDto.java
  server/src/main/java/com/jamit/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/jamit/member/dto/MemberDto.java
  server/src/main/java/com/jamit/member/dto/ProfileDto.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
Labels: 🔧 refactor, [BE]정우용

#130 [client] 댓글 구현
  client/package-lock.json
  client/package.json
  client/public/img/delete.png
  client/public/img/edit.png
  client/public/img/edit_move.gif
  client/src/Components/Header/AccountMenu.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/jamDetailComponent/JamComments.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/jamDetailComponent/ReplyComment.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/UserName.js
  client/src/Pages/JamDetail.js
  client/src/Pages/Landing.js
  client/src/Pages/Login.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: :sparkles: feat, [FE]김재훈

#135 [client] 지도에 지역별 잼 마커 표시 기능 추가
  client/src/Components/Map/Map.js
  client/src/Pages/Home.js
  client/src/Utils/fetchJam.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#137 [client] 검색 기능 구현
  client/src/Components/Category/CategoryResult.js
  client/src/Components/Header/Header.js
  client/src/Utils/fetchJam.js
Labels: :sparkles: feat, [FE]노민하

#139 [client] 대댓글 구현
  client/src/Components/JamColor.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/userComp/UserName.js
  client/src/Pages/JamDetail.js
  client/src/Pages/Mypage.js
Labels: :sparkles: feat, [FE]김재훈

#142 [server] 유저에서 참여자 프로필 이미지 가져오기
  server/src/main/java/com/jamit/jam/dto/ResponseParticipantDto.java
  server/src/main/java/com/jamit/jam/mapper/JamMapper.java
Labels: :sparkles: feat, [BE]손경은

#143 [client] 검색, 카테고리, 잼 상세 연동
  client/src/Components/Category/CategoryResult.js
  client/src/Components/Category/JamCard.js
  client/src/Components/Category/LongJamCard.js
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/Landing/Categories.js
  client/src/Components/NoData.js
  client/src/Components/Sidebar.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#145 [client] 잼 상세 위치 지도 구현, 잼 모집, 참여와 취소 수정, 이미지 업로드 구현
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamCreateComponent/KakaoMap.js
  client/src/Components/jamCreateComponent/MapLanding.js
  client/src/Components/jamCreateComponent/Uploader.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamLocationMap.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
  client/src/Pages/Profile.js
Labels: :bug: bug, :sparkles: feat, [FE]김정구

#147 [client] 각종 버그수정 및 페이지 수정
  client/src/Atom/atoms.js
  client/src/Components/Header/AccountMenu.js
  client/src/Components/JamColor.js
  client/src/Components/SignComp/ForgetPassword.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/JamElapsedTime.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/JoinJams.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Components/userComp/OpenJams.js
  client/src/Components/userComp/UserName.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/JamDetail.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: :bug: bug, :sparkles: feat, [FE]김재훈

#148 [client] 지도 오류 수정
  client/src/Components/Map/Map.js
  client/src/Pages/Home.js
Labels: :sparkles: feat, [FE]노민하

#158 [client] 배포 오류 수정
  client/src/components/Button.js
  client/src/components/jamDetailComponent/JamComments.js
  client/src/components/jamDetailComponent/JamInfo.js
  client/src/components/jamDetailComponent/JamSideBar.js
  client/src/components/jamDetailComponent/ReReplyComment.js
  client/src/components/jamDetailComponent/RecruitState.js
  client/src/components/jamDetailComponent/ReplyComment.js
  client/src/components/jamDetailComponent/WriteComment.js
  client/src/pages/JamDetail.js
Labels: :bug: bug, [FE]노민하

#152 [server] 전체 잼 조회 이미지 추가
  server/src/main/java/com/jamit/comment/dto/ResponseCommentDto.java
  server/src/main/java/com/jamit/comment/mapper/CommentMapper.java
  server/src/main/java/com/jamit/jam/dto/ResponseAllJamsDto.java
Labels: :sparkles: feat, [BE]손경은

#154 [server] 댓글에 멤버 프로필 이미지, 평점 추가
  server/src/main/java/com/jamit/comment/dto/ResponseCommentDto.java
  server/src/main/java/com/jamit/comment/mapper/CommentMapper.java
Labels: :sparkles: feat, [BE]손경은

#156 [server] 대댓글에 멤버 프로필 이미지, 평점 추가
  server/src/main/java/com/jamit/reply/dto/ResponseReplyDto.java
  server/src/main/java/com/jamit/reply/mapper/ReplyMapper.java
Labels: :sparkles: feat, [BE]손경은

#161 [client] 페이지 테스트 오류 개선 및 이미지 연결
  client/src/Components/Category/JamCard.js
  client/src/Components/Category/LongJamCard.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Pages/JamMake.js
Labels: :bug: bug, :sparkles: feat, 🎨 style, 🔍 chore, [FE]김정구

#164 [client] vercel 프론트 배포 오류 수정사항 반영
  client/package-lock.json
  client/src/Components/SignComp/ForgetPassword.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/userComp/GiveJam.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: :bug: bug, [FE]김재훈, [FE]김정구, [FE]노민하, ⚗️ test

#167 [client] 추가작업
  client/package-lock.json
  client/public/favicon.ico
  client/public/index.html
  client/src/Atom/atoms.js
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/JamElapsedTime.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Pages/JamDetail.js
Labels: :sparkles: feat, [FE]김재훈

#169 [client] 페이지별 보완사항 수정
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/userComp/UserName.js
Labels: :bug: bug, [FE]김정구

#172 [server] 유저 평점 리팩토링
  server/src/main/generated/com/jamit/jam/mapper/JamMapperImpl.java
  server/src/main/generated/com/jamit/member/mapper/MemberMapperImpl.java
  server/src/main/java/com/jamit/member/entity/Grade.java
  server/src/main/java/com/jamit/member/entity/Member.java
  server/src/main/java/com/jamit/member/repository/GradeRepository.java
  server/src/main/java/com/jamit/member/service/MemberService.java
Labels: 🔧 refactor, [BE]이지연

#173 [client] 페이지네이션 오류 수정
  client/src/Components/Card/JamPagination.js
  client/src/Pages/CategoryResult.js
Labels: :bug: bug, [FE]노민하

#174 [client] 마감된 잼의 참여 버튼 활성화 상태 수정
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReply.js
Labels: :bug: bug, [FE]김재훈, [FE]김정구, [FE]노민하

#178 [client] 잼 수정시 발생 오류 조치
  client/src/Components/jamCreateComponent/EditButtonGroup.js
Labels: :bug: bug, [FE]김정구

#179 [client] 최종 배포
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/Atom/atoms.js
  client/src/Components/Card/JamCard.js
  client/src/Components/Card/JamPagination.js
  client/src/Components/Card/LongJamCard.js
  client/src/Components/JamColor.js
  client/src/Components/SignComp/ForgetPassword.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/JamElapsedTime.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Components/userComp/UserName.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/CategoryResult.js
  client/src/Pages/Home.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: [FE]김재훈, [FE]김정구, [FE]노민하

#182 [client] 배포 마무리
  client/src/Components/Card/JamCard.js
  client/src/Components/Card/JamPagination.js
  client/src/Components/Card/LongJamCard.js
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/JamColor.js
  client/src/Components/Landing/Btn.js
  client/src/Components/Landing/Categories.js
  client/src/Components/Landing/Hero.js
  client/src/Components/Landing/HowItWorks.js
  client/src/Components/Landing/Typography.js
  client/src/Components/Landing/Values.js
  client/src/Components/Map/Map.js
  client/src/Components/NoData.js
  client/src/Components/Sidebar.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/jamCreateComponent/Description.js
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamCreateComponent/FileUploader.js
  client/src/Components/jamCreateComponent/JamInputField.js
  client/src/Components/jamCreateComponent/KakaoMap.js
  client/src/Components/jamCreateComponent/KewordAddressModal.js
  client/src/Components/jamCreateComponent/MapLanding.js
  client/src/Components/jamCreateComponent/StudyInputField.js
  client/src/Components/jamCreateComponent/Uploader.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamComments.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamLocationMap.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReplyComment.js
  client/src/Components/jamDetailComponent/ReplyComment.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/CategoryResult.js
  client/src/Pages/Home.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
  client/src/Pages/Landing.js
  client/src/Pages/Profile.js
  client/src/Utils/customAxios.js
  client/src/Utils/fetchJam.js
Labels: 🔍 chore, [FE]김재훈, [FE]김정구, [FE]노민하

#184 [client] 최종 배포를 위한 충돌 수정
  client/src/Components/Card/JamCard.js
  client/src/Components/Card/JamPagination.js
  client/src/Components/Card/LongJamCard.js
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/JamColor.js
  client/src/Components/Landing/Btn.js
  client/src/Components/Landing/Categories.js
  client/src/Components/Landing/Hero.js
  client/src/Components/Landing/HowItWorks.js
  client/src/Components/Landing/Typography.js
  client/src/Components/Landing/Values.js
  client/src/Components/Map/Map.js
  client/src/Components/NoData.js
  client/src/Components/Sidebar.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/jamCreateComponent/Description.js
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamCreateComponent/FileUploader.js
  client/src/Components/jamCreateComponent/JamInputField.js
  client/src/Components/jamCreateComponent/KakaoMap.js
  client/src/Components/jamCreateComponent/KewordAddressModal.js
  client/src/Components/jamCreateComponent/MapLanding.js
  client/src/Components/jamCreateComponent/StudyInputField.js
  client/src/Components/jamCreateComponent/Uploader.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamComments.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamLocationMap.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReplyComment.js
  client/src/Components/jamDetailComponent/ReplyComment.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/CategoryResult.js
  client/src/Pages/Home.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
  client/src/Pages/Landing.js
  client/src/Pages/Profile.js
  client/src/Utils/customAxios.js
  client/src/Utils/fetchJam.js
Labels: 🔍 chore, [FE]김재훈, [FE]김정구, [FE]노민하

#186 [client] 검색 결과 페이지네이션 오류 수정
  client/src/Atom/atoms.js
  client/src/Components/Card/JamPagination.js
  client/src/Pages/CategoryResult.js
Labels: :bug: bug, [FE]노민하

#188 [client] 오픈그래프 설정 추가
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
Labels: 🔍 chore, [FE]노민하

#189 feat: 유저 프로필 잼 상태 추가
  server/build.gradle
  server/src/main/java/com/jamit/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/jamit/config/SecurityConfiguration.java
  server/src/main/java/com/jamit/member/dto/ProfileDto.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
  server/src/main/resources/application.yml
Labels: :sparkles: feat, [BE]정우용

#192 [client] 지도 이동시 상단 동네 정보를 수정기능 추가
  client/src/Components/Map/Map.js
Labels: :sparkles: feat, [FE]노민하

#196 [client] 지도 이동시 중심 동네로 바로 이동하는 오류 수정
  client/src/Atom/atoms.js
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Map/Map.js
Labels: :bug: bug, [FE]노민하

#194 [server] Return Response Body to Comment
  server/src/main/java/com/jamit/comment/controller/CommentController.java
Labels: 🔧 refactor, [BE]손경은

#197 [server] Return Response Body to Reply
  server/src/main/java/com/jamit/reply/controller/ReplyController.java
  server/src/main/java/com/jamit/reply/dto/ResponseReplyDto.java
Labels: 🔧 refactor, [BE]손경은

#199 [server] merge dev-be to main
  server/build.gradle
  server/src/main/java/com/jamit/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/jamit/comment/controller/CommentController.java
  server/src/main/java/com/jamit/config/SecurityConfiguration.java
  server/src/main/java/com/jamit/member/dto/ProfileDto.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
  server/src/main/java/com/jamit/reply/controller/ReplyController.java
  server/src/main/java/com/jamit/reply/dto/ResponseReplyDto.java
  server/src/main/resources/application.yml
Labels: [BE]손경은, [BE]이지연, [BE]정우용

#203 [client] 오류 수정
  .DS_Store
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Pages/JamDetail.js
Labels: :bug: bug, [FE]김재훈

#204 [client] 잼 작성과 수정시 오류 수정
  client/package-lock.json
  client/src/Components/Header/Header.js
  client/src/Components/jamCreateComponent/KakaoMap.js
  client/src/Components/jamCreateComponent/Uploader.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Pages/JamMake.js
Labels: :bug: bug, [FE]김정구

#205 [client] merge dev-be to main
  .DS_Store
  client/package-lock.json
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/Assets/images/map_pin.png
  client/src/Atom/atoms.js
  client/src/Components/Card/JamPagination.js
  client/src/Components/Card/LongJamCard.js
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/Map/Map.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/jamCreateComponent/KakaoMap.js
  client/src/Components/jamCreateComponent/Uploader.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamLocationMap.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Pages/CategoryResult.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
Labels: [FE]김재훈, [FE]김정구, [FE]노민하

#206 [server] 소셜로그인, 토큰 재발급 API 추가
  server/src/main/java/com/jamit/auth/Controller/AuthController.java
  server/src/main/java/com/jamit/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/jamit/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/jamit/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/jamit/member/controller/OAuthController.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/my-page.html
  server/src/main/resources/templates/receive-token.html
Labels: :sparkles: feat, [BE]정우용

#209 [client] 반응형(mypage, profile)
  client/package-lock.json
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
  client/src/setupProxy.js
Labels: 🎨 style, [FE]김재훈

#213 [client] 대댓글 추가작업
  .DS_Store
  client/src/Components/jamDetailComponent/ReReply.js
  client/src/Components/jamDetailComponent/Reply.js
  client/src/Pages/JamDetail.js
Labels: :sparkles: feat, [FE]김재훈

#215 [client] 헤더, 카테고리 디자인 반응형으로 수정
  .DS_Store
  client/package-lock.json
  client/src/Components/Card/JamCard.js
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/Sidebar.js
  client/src/Pages/CategoryResult.js
  client/src/Pages/Home.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: 🎨 style, [FE]노민하

#218 [client] LongJamCard 반응형 디자인 추가
  client/src/Components/Card/LongJamCard.js
  client/src/Pages/Home.js
Labels: 🎨 style, [FE]노민하

#220 [client] 홈 화면 반응형 디자인 수정
  client/src/Components/FloatingButton.js
  client/src/Components/Header/Header.js
  client/src/Pages/CategoryResult.js
  client/src/Pages/Home.js
Labels: 🎨 style, [FE]노민하

#222 [client] 헤더 drawer 추가
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/Header/MenuDrawer.js
  client/src/Components/Map/Map.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#225 [client] 모바일 세부작업
  client/package-lock.json
  client/src/Components/Header/AccountMenu.js
  client/src/Components/Header/MenuDrawer.js
  client/src/Components/userComp/Logout.js
  client/src/Pages/Landing.js
Labels: :sparkles: feat, [FE]김재훈

#226 [client] 이미지 버그 수정
  client/src/Components/Header/AccountMenu.js
  client/src/Components/Header/MenuDrawer.js
  client/src/Components/userComp/Logout.js
Labels: :bug: bug, [FE]김재훈

#227 [client] 모바일용 검색페이지 제작
  client/src/App.js
  client/src/Components/Header/Header.js
  client/src/Pages/CategoryResult.js
  client/src/Pages/Home.js
  client/src/Pages/Search.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#229 [client] 검색어가 없을때 '검색 결과입니다' 텍스트 보이지 않도록 수정
  client/src/Pages/CategoryResult.js
Labels: :bug: bug, [FE]노민하

#230 [client] 잼 개설페이지, 상세페이지 반응형 추가 작업 및 수정
  client/src/Components/jamCreateComponent/KakaoMap.js
  client/src/Components/jamCreateComponent/KewordAddressModal.js
  client/src/Components/jamCreateComponent/StudyInputField.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamSideBarStateMedia.js
  client/src/Components/jamDetailComponent/RecruitState.js
  client/src/Pages/JamDetail.js
  client/src/Styles/pickerStyles.css
Labels: :bug: bug, 🎨 style, 🔍 chore, [FE]김정구

#232 [client] 헤더 & drawer 유저 오류 수정
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/Header/MenuDrawer.js
  client/src/Components/userComp/Logout.js
Labels: :bug: bug, 🎨 style, [FE]노민하

#233 [client] 레이아웃 수정
  client/src/Pages/Profile.js
Labels: 🎨 style, [FE]김재훈

#236 [client] 잼 상세페이지 스터디 위치 오버레이 수정
  client/src/Components/jamDetailComponent/JamLocationMap.js
Labels: 🎨 style, [FE]김정구, [FE]노민하
