Repository codestates-seb/seb40_main_006, pull requests merged in 2022-11, with the labels that each got.

#3 [server] feat: 공통 클래스 추가
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/src/main/java/com/jamit/JamitApplication.java
  server/src/main/java/com/jamit/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/jamit/audit/Auditable.java
  server/src/main/java/com/jamit/dto/MultiResponseDto.java
  server/src/main/java/com/jamit/dto/PageInfo.java
  server/src/main/java/com/jamit/dto/SingleResponseDto.java
  server/src/main/java/com/jamit/exception/BusinessLogicException.java
  server/src/main/java/com/jamit/exception/ExceptionCode.java
  server/src/main/java/com/jamit/response/ErrorResponse.java
Labels: 🔍 chore

#6 [client] feat: 클라이언트 초기 세팅
  client/.eslintrc
  client/.gitignore
  client/.prettierrc.js
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/Atom/atoms.js
  client/src/Styles/App.css
  client/src/Styles/global.js
  client/src/Styles/index.css
  client/src/Styles/theme.js
  client/src/index.js
Labels: 🔍 chore

#11 [server] chore: 공통 클래스 관리
  server/src/main/java/com/jamit/global/audit/Auditable.java
  server/src/main/java/com/jamit/global/dto/MultiResponseDto.java
  server/src/main/java/com/jamit/global/dto/PageInfo.java
  server/src/main/java/com/jamit/global/dto/SingleResponseDto.java
Labels: 🔍 chore, [BE]손경은

#12 [server] feat: 엔티티 연관관계 매핑
  server/src/main/java/com/jamit/comment/entity/Comment.java
  server/src/main/java/com/jamit/jam/entity/Category.java
  server/src/main/java/com/jamit/jam/entity/Jam.java
  server/src/main/java/com/jamit/member/entity/Member.java
  server/src/main/java/com/jamit/member/repository/MemberRepository.java
  server/src/main/java/com/jamit/member/service/MemberService.java
  server/src/main/java/com/jamit/reply/entity/Reply.java
Labels: :sparkles: feat, [BE]손경은, [BE]이지연, [BE]정우용

#14 [server] feat: 엔티티 연관관계 매핑
  server/src/main/java/com/jamit/reply/entity/Reply.java
Labels: :sparkles: feat, [BE]손경은

#17 [server] feat: 연관관계 편의메서드 구현
  server/src/main/java/com/jamit/comment/entity/Comment.java
  server/src/main/java/com/jamit/jam/entity/Category.java
  server/src/main/java/com/jamit/jam/entity/Jam.java
  server/src/main/java/com/jamit/member/entity/Member.java
  server/src/main/java/com/jamit/reply/entity/Reply.java
Labels: :sparkles: feat, [BE]손경은

#20 [client] style: 잼 개설, 상세, 수정 페이지 구현
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/components/Button.js
  client/src/components/jamDetailComponent/JamComments.js
  client/src/components/jamDetailComponent/JamInfo.js
  client/src/components/jamDetailComponent/JamSideBar.js
  client/src/components/jamDetailComponent/ReReplyComment.js
  client/src/components/jamDetailComponent/RecruitState.js
  client/src/components/jamDetailComponent/ReplyComment.js
  client/src/components/jamDetailComponent/WriteComment.js
  client/src/components/jamOpenComponent/Description.js
  client/src/components/jamOpenComponent/EditButtonGroup.js
  client/src/components/jamOpenComponent/JamInputField.js
  client/src/components/jamOpenComponent/StudyInputField.js
  client/src/pages/JamDetail.js
  client/src/pages/JamOpen.js
Labels: 🎨 style, [FE]김정구

#21 [client] style: 회원가입, 로그인, 유저정보수정, 마이페이지 구현
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/public/img/orangeJam.png
  client/src/App.js
  client/src/Components/SignComp/BackgroundImage.js
  client/src/Components/SignComp/LoginHelp.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/userComp/AvatarImg.js
  client/src/Components/userComp/JamCard.js
  client/src/Components/userComp/JoinJams.js
  client/src/Components/userComp/OpenJams.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/Login.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
  client/src/Pages/Signup.js
  client/src/Styles/App.css
  client/src/Styles/index.css
  client/src/Styles/theme.js
  client/src/index.js
Labels: 🎨 style, [FE]김재훈

#23 [client] style: 헤더, 사이드바, 홈 화면 ui 구현
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Assets/images/logo_header.png
  client/src/Components/Category/Category.js
  client/src/Components/Category/JamCard.js
  client/src/Components/Category/LongJamCard.js
  client/src/Components/Header.js
  client/src/Components/Sidebar.js
  client/src/Pages/Home.js
  client/src/Styles/global.js
  client/src/Styles/theme.js
  client/src/components/jamDetailComponent/ReReplyComment.js
  client/src/components/jamDetailComponent/ReplyComment.js
  client/src/components/jamDetailComponent/WriteComment.js
  client/src/components/jamOpenComponent/EditButtonGroup.js
  client/src/pages/JamDetail.js
  client/src/pages/JamOpen.js
Labels: 🎨 style, [FE]노민하

#28 [client] feat: home 화면에 카카오맵 추가
  client/.gitignore
  client/public/index.html
  client/src/App.js
  client/src/Components/Map/Map.js
  client/src/Pages/Home.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#30 [server] feat: Jam 기본 CRUD 구현
  server/build.gradle
  server/src/main/java/com/jamit/auth/dto/LoginDto.java
  server/src/main/java/com/jamit/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/jamit/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/jamit/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/jamit/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/jamit/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/jamit/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/jamit/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/jamit/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/jamit/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/jamit/auth/utils/ErrorResponder.java
  server/src/main/java/com/jamit/config/SecurityConfiguration.java
  server/src/main/java/com/jamit/exception/ExceptionCode.java
  server/src/main/java/com/jamit/jam/controller/JamController.java
  server/src/main/java/com/jamit/jam/dto/JamPatchDto.java
  server/src/main/java/com/jamit/jam/dto/JamPostDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseAllJamsDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseParticipantDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseSpecificJamDto.java
  server/src/main/java/com/jamit/jam/entity/Jam.java
  server/src/main/java/com/jamit/jam/mapper/JamMapper.java
  server/src/main/java/com/jamit/jam/repository/JamRepository.java
  server/src/main/java/com/jamit/jam/service/JamService.java
  server/src/main/java/com/jamit/member/controller/MemberController.java
  server/src/main/java/com/jamit/member/dto/MemberDto.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
  server/src/main/java/com/jamit/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: :sparkles: feat, [BE]손경은

#32 [client] style: 페이지 디자인 수정 및 UI 추가 반영, 입력 폼 데이터값 출력
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/jamCreateComponent/Description.js
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamCreateComponent/FileUploader.js
  client/src/Components/jamCreateComponent/JamInputField.js
  client/src/Components/jamCreateComponent/StudyInputField.js
  client/src/Components/jamDetailComponent/JamCarousel.js
  client/src/Pages/JamCreate.js
  client/src/components/jamDetailComponent/JamComments.js
  client/src/components/jamDetailComponent/JamInfo.js
  client/src/components/jamDetailComponent/JamSideBar.js
  client/src/components/jamDetailComponent/ReplyComment.js
  client/src/components/jamDetailComponent/WriteComment.js
  client/src/pages/JamDetail.js
  client/src/pages/JamOpen.js
Labels: :sparkles: feat, 🎨 style, [FE]김정구

#37 [server] feat: 일반 검색 구현
  server/src/main/generated/com/jamit/location/mapper/LocationMapperImpl.java
  server/src/main/java/com/jamit/jam/controller/JamController.java
  server/src/main/java/com/jamit/jam/dto/JamResponseDto.java
  server/src/main/java/com/jamit/jam/repository/JamRepository.java
  server/src/main/java/com/jamit/jam/service/JamService.java
  server/src/main/java/com/jamit/location/mapper/LocationMapper.java
  server/src/main/java/com/jamit/location/service/LocationService.java
  server/src/main/java/com/jamit/location/utility/GeometryUtil.java
Labels: :sparkles: feat, [BE]이지연

#38 test: v1 AWS 배포
  server/build.gradle
  server/src/main/java/com/jamit/JamitApplication.java
  server/src/main/java/com/jamit/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/jamit/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/jamit/auth/userdetails/MemberDetails.java
  server/src/main/java/com/jamit/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/jamit/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/jamit/config/SecurityConfiguration.java
  server/src/main/java/com/jamit/jam/dto/JamResponseDto.java
  server/src/main/java/com/jamit/jam/entity/Category.java
  server/src/main/java/com/jamit/member/controller/MemberController.java
  server/src/main/java/com/jamit/member/dto/MemberDto.java
  server/src/main/java/com/jamit/member/entity/Member.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
  server/src/main/java/com/jamit/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: [BE]손경은, [BE]이지연, [BE]정우용, ⚗️ test

#39 [client] 잘못된 주소 접근, 검색 결과 없음 컴포넌트 제작
  client/src/App.js
  client/src/Assets/images/bx_error.png
  client/src/Components/Category/CategoryResult.js
  client/src/Components/Search/NoData.js
  client/src/Pages/NotFound.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#40 [client] 마이페이지, 프로필 수정 페이지 기능구현
  client/package-lock.json
  client/public/img/userInitImg.png
  client/public/img/userLocation.png
  client/public/img/userTime.png
  client/src/Atom/atoms.js
  client/src/Components/userComp/JamCard.js
  client/src/Components/userComp/JamElapsedTime.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/JoinJams.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Components/userComp/OpenJams.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: :sparkles: feat, 🎨 style, [FE]김재훈

#43 [server] 잼 참여 / 취소 구현
  server/src/main/java/com/jamit/jam/controller/JamParticipantController.java
  server/src/main/java/com/jamit/jam/dto/JamPatchDto.java
  server/src/main/java/com/jamit/jam/dto/JamPostDto.java
  server/src/main/java/com/jamit/jam/dto/JamResponseDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseAllJamsDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseParticipantDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseSpecificJamDto.java
  server/src/main/java/com/jamit/jam/entity/Jam.java
  server/src/main/java/com/jamit/jam/entity/JamParticipant.java
  server/src/main/java/com/jamit/jam/mapper/JamMapper.java
  server/src/main/java/com/jamit/jam/repository/JamParticipantRepository.java
  server/src/main/java/com/jamit/jam/service/JamParticipantService.java
  server/src/main/java/com/jamit/jam/service/JamService.java
  server/src/main/java/com/jamit/jam/status/ParticipantStatus.java
  server/src/main/java/com/jamit/member/service/MemberService.java
Labels: :sparkles: feat, 🔍 chore, [BE]손경은

#48 [client] 로그인, 회원가입 페이지 기능 구현
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Atom/atoms.js
  client/src/Components/SignComp/Cookie.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/userComp/JoinJams.js
  client/src/Components/userComp/OpenJams.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: :sparkles: feat, [FE]김재훈

#51 [server] Jam Comment CUD 구현
  server/src/main/java/com/jamit/comment/controller/CommentController.java
  server/src/main/java/com/jamit/comment/dto/CommentPatchDto.java
  server/src/main/java/com/jamit/comment/dto/CommentPostDto.java
  server/src/main/java/com/jamit/comment/dto/ResponseCommentDto.java
  server/src/main/java/com/jamit/comment/entity/Comment.java
  server/src/main/java/com/jamit/comment/mapper/CommentMapper.java
  server/src/main/java/com/jamit/comment/repository/CommentRepository.java
  server/src/main/java/com/jamit/comment/service/CommentService.java
  server/src/main/java/com/jamit/exception/ExceptionCode.java
  server/src/main/java/com/jamit/global/utils/Check.java
  server/src/main/java/com/jamit/jam/dto/ResponseSpecificJamDto.java
  server/src/main/java/com/jamit/jam/mapper/JamMapper.java
  server/src/main/java/com/jamit/jam/service/JamService.java
  server/src/main/java/com/jamit/member/service/MemberService.java
  server/src/main/java/com/jamit/reply/dto/ReplyResponseDto.java
  server/src/main/java/com/jamit/reply/dto/ResponseReplyDto.java
  server/src/main/java/com/jamit/reply/mapper/ReplyMapper.java
  server/src/main/resources/static/db/data.sql
Labels: :sparkles: feat, 🔍 chore, [BE]손경은

#53 [client] 헤더에서 동네 입력받아 홈화면에 해당 동 카카오맵 띄우기
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Atom/atoms.js
  client/src/Components/Header/AddressDialog.js
  client/src/Components/Header/Header.js
  client/src/Components/Header/getJuso.js
  client/src/Components/Map/Map.js
  client/src/Pages/Home.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#54 #47 feat: 댓글, 잼 참여 기능 유저 권한 부여
  server/src/main/java/com/jamit/comment/controller/CommentController.java
  server/src/main/java/com/jamit/jam/controller/JamParticipantController.java
Labels: :sparkles: feat, [BE]정우용

#57 #50 feat: 유저 프로필 구현
  server/src/main/java/com/jamit/member/controller/MemberController.java
  server/src/main/java/com/jamit/member/dto/ProfileDto.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
  server/src/main/java/com/jamit/member/profile/CreateJam.java
  server/src/main/java/com/jamit/member/profile/JoinJam.java
  server/src/main/java/com/jamit/member/profile/ProfileResponse.java
Labels: :sparkles: feat, [BE]정우용

#58 [client] 홈, 카테고리 세부 디자인 수정
  client/src/Atom/atoms.js
  client/src/Components/Category/CategoryResult.js
  client/src/Components/Category/JamCard.js
  client/src/Components/Category/LongJamCard.js
  client/src/Components/Header/Header.js
  client/src/Components/Sidebar.js
Labels: 🎨 style, 🔧 refactor, [FE]노민하

#59 [client] 잼 개설 페이지 기능 구현
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/Components/jamCreateComponent/AddressModal.js
  client/src/Components/jamCreateComponent/Description.js
  client/src/Components/jamCreateComponent/EditButtonGroup.js
  client/src/Components/jamCreateComponent/FileUploader.js
  client/src/Components/jamCreateComponent/JamInputField.js
  client/src/Components/jamCreateComponent/KakaoMap.js
  client/src/Components/jamCreateComponent/KewordAddressModal.js
  client/src/Components/jamCreateComponent/MapLanding.js
  client/src/Components/jamCreateComponent/StudyInputField.js
  client/src/Components/jamCreateComponent/Uploader.js
  client/src/Pages/JamCreate.js
  client/src/Pages/JamEdit.js
  client/src/Pages/JamMake.js
  client/src/components/jamDetailComponent/JamInfo.js
  client/src/pages/JamDetail.js
Labels: :sparkles: feat, [FE]김정구

#62 [client] 유저평가기능
  client/public/img/jam.png
  client/public/img/whiteJam.png
  client/src/Atom/atoms.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/Mypage.js
  client/src/Pages/Profile.js
Labels: :sparkles: feat, 🎨 style, [FE]김재훈

#66 [client] 파일 디렉토리 변경
  client/src/Components/Button.js
  client/src/Components/jamDetailComponent/JamComments.js
  client/src/Components/jamDetailComponent/JamInfo.js
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReplyComment.js
  client/src/Components/jamDetailComponent/RecruitState.js
  client/src/Components/jamDetailComponent/ReplyComment.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Pages/JamDetail.js
Labels: [FE]김재훈, [FE]김정구, [FE]노민하

#70 [client] 잼 세부 디자인 수정
  client/src/Components/jamDetailComponent/JamSideBar.js
  client/src/Components/jamDetailComponent/ReReplyComment.js
  client/src/Components/jamDetailComponent/ReplyComment.js
  client/src/Pages/JamDetail.js
  client/src/Pages/JamMake.js
Labels: 🎨 style, [FE]노민하

#73 [client] 로그인시 토큰 저장, 로그인,회원가입 통신
  client/package-lock.json
  client/package.json
  client/src/Atom/atoms.js
  client/src/Components/SignComp/Sign.js
Labels: :sparkles: feat, [FE]김재훈

#75 [client] 상단바 메뉴
  client/package-lock.json
  client/src/Components/Header/AccountMenu.js
  client/src/Components/Header/Header.js
  client/src/Styles/global.js
Labels: :sparkles: feat, 🎨 style, [FE]김재훈

#78 [client] 비밀번호 찾기 기능
  client/src/Components/SignComp/ForgetPassword.js
  client/src/Components/SignComp/LoginHelp.js
  client/src/Pages/Login.js
Labels: :sparkles: feat, 🎨 style, [FE]김재훈

#81 [client] axios custom
  client/src/Components/SignComp/Sign.js
  client/src/customAxios.js
Labels: :sparkles: feat, [FE]김재훈

#79 [server] 분야 / 지역 별 조회 구현
  server/src/main/java/com/jamit/jam/controller/JamController.java
  server/src/main/java/com/jamit/jam/mapper/JamMapper.java
  server/src/main/java/com/jamit/jam/repository/JamRepository.java
Labels: :sparkles: feat, [BE]손경은

#82 [server] 잼 완료 / 취소하기
  server/src/main/java/com/jamit/JamitApplication.java
  server/src/main/java/com/jamit/exception/ExceptionCode.java
  server/src/main/java/com/jamit/global/scheduler/JamScheduler.java
  server/src/main/java/com/jamit/global/utils/Check.java
  server/src/main/java/com/jamit/jam/controller/JamCompleteController.java
  server/src/main/java/com/jamit/jam/controller/JamController.java
  server/src/main/java/com/jamit/jam/dto/JamPatchDto.java
  server/src/main/java/com/jamit/jam/dto/JamPostDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseAllJamsDto.java
  server/src/main/java/com/jamit/jam/dto/ResponseSpecificJamDto.java
  server/src/main/java/com/jamit/jam/entity/Jam.java
  server/src/main/java/com/jamit/jam/mapper/JamMapper.java
  server/src/main/java/com/jamit/jam/repository/JamRepository.java
  server/src/main/java/com/jamit/jam/service/JamCompleteService.java
  server/src/main/java/com/jamit/jam/service/JamService.java
  server/src/main/java/com/jamit/jam/status/CompleteStatus.java
  server/src/main/java/com/jamit/member/mapper/MemberMapper.java
Labels: :sparkles: feat, 🔍 chore, [BE]손경은

#85 [server] 검색 페이지네이션, 글 작성 수정에 포인트 저장 로직 추가
  server/gradlew
  server/src/main/java/com/jamit/jam/controller/JamController.java
  server/src/main/java/com/jamit/jam/repository/JamRepository.java
  server/src/main/java/com/jamit/jam/service/JamService.java
Labels: 🔧 refactor, [BE]이지연

#87 [server] 임시 비밀번호 기능 추가
  server/src/main/java/com/jamit/auth/dto/LoginResponseDto.java
  server/src/main/java/com/jamit/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/jamit/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/jamit/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/jamit/comment/controller/CommentController.java
  server/src/main/java/com/jamit/exception/ExceptionCode.java
  server/src/main/java/com/jamit/jam/controller/JamParticipantController.java
  server/src/main/java/com/jamit/jam/service/JamService.java
  server/src/main/java/com/jamit/member/controller/MemberController.java
  server/src/main/java/com/jamit/member/dto/MemberDto.java
  server/src/main/java/com/jamit/member/entity/Member.java
  server/src/main/java/com/jamit/member/repository/MemberRepository.java
  server/src/main/java/com/jamit/member/service/MemberService.java
  server/src/main/resources/application.yml
Labels: :sparkles: feat, [BE]정우용

#94 [client] 카테고리별 잼 read 기능 추가
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/Atom/atoms.js
  client/src/Components/Category/CategoryResult.js
  client/src/Components/Category/JamCard.js
  client/src/Components/Map/Map.js
  client/src/Components/NoData.js
  client/src/Components/Sidebar.js
  client/src/Static/categories.js
  client/src/Utils/fetchJam.js
Labels: :sparkles: feat, 🎨 style, [FE]노민하

#96 [client] 유저 통신
  client/package-lock.json
  client/package.json
  client/src/Atom/atoms.js
  client/src/Components/Header/AccountMenu.js
  client/src/Components/Header/Header.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/jamDetailComponent/ReplyComment.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/GiveJam.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/JoinJams.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Components/userComp/OpenJams.js
  client/src/Components/userComp/UserName.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/Mypage.js
Labels: :sparkles: feat, [FE]김재훈

#98 [client] 렌딩페이지 수정
  client/src/App.js
  client/src/Components/Landing/Btn.js
  client/src/Components/Landing/Categories.js
  client/src/Components/Landing/Hero.js
  client/src/Components/Landing/HeroLayout.js
  client/src/Components/Landing/HowItWorks.js
  client/src/Components/Landing/Typography.js
  client/src/Components/Landing/Values.js
  client/src/Components/Landing/Works.js
  client/src/Pages/Landing.js
Labels: 🎨 style, [FE]김재훈

#103 [server] 파일 업로드 구현
  server/src/main/java/com/jamit/File/controller/FileUploadController.java
  server/src/main/java/com/jamit/File/repository/S3UploadRepository.java
  server/src/main/java/com/jamit/File/repository/UploadRepository.java
  server/src/main/java/com/jamit/File/service/FileUploadService.java
  server/src/main/java/com/jamit/File/service/S3Component.java
  server/src/main/java/com/jamit/File/service/S3Uploader.java
  server/src/main/java/com/jamit/JamitApplication.java
  server/src/main/java/com/jamit/config/S3Configuration.java
  server/src/main/resources/application.yml
Labels: :sparkles: feat, [BE]손경은

#104 [client] 프로필수정페이지 통신
  client/package.json
  client/src/Components/Header/AccountMenu.js
  client/src/Components/Landing/Works.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/userComp/AvatarImg.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/Profile.js
Labels: :sparkles: feat, [FE]김재훈

#107 [client] 유저 평점 잼부여
  .DS_Store
  client/public/img/whiteJam.png
  client/src/Atom/atoms.js
  client/src/Components/Header/AccountMenu.js
  client/src/Components/JamColor.js
  client/src/Components/Landing/Values.js
  client/src/Components/Landing/Works.js
  client/src/Components/SignComp/Sign.js
  client/src/Components/SignComp/SocialLogin.js
  client/src/Components/jamDetailComponent/WriteComment.js
  client/src/Components/userComp/JoinJamCard.js
  client/src/Components/userComp/OpenJamCard.js
  client/src/Components/userComp/UserName.js
  client/src/Components/userComp/UserTitle.js
  client/src/Pages/Mypage.js
Labels: :sparkles: feat, 🎨 style, [FE]김재훈

#111 [server] add aws dependency
  server/build.gradle
Labels: 🔍 chore, [BE]손경은
